# Generated by Django 5.2.1 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sedentary", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("birth_year", models.CharField(max_length=4)),
            ],
        ),
    ]
