# Generated by Django 5.2.1 on 2025-06-08 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyresponse",
            name="birth_year",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="sedentary",
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="drinking",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="exercise",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="fatigue",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="indoor_daytime",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="responses",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="sitting_work",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="sleep_well",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="smoking",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="still_tired",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SurveyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("sitting_work", models.BooleanField(blank=True, null=True)),
                ("indoor_daytime", models.BooleanField(blank=True, null=True)),
                ("exercise", models.BooleanField(blank=True, null=True)),
                ("smoking", models.BooleanField(blank=True, null=True)),
                ("drinking", models.BooleanField(blank=True, null=True)),
                ("fatigue", models.BooleanField(blank=True, null=True)),
                ("sleep_well", models.BooleanField(blank=True, null=True)),
                ("still_tired", models.BooleanField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                (
                    "exercise_frequency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("water_intake", models.IntegerField(blank=True, null=True)),
                (
                    "current_supplements",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("allergies", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "health_concerns",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
