# Generated by Django 5.2.1 on 2025-06-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0002_remove_surveyresponse_birth_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("benefits", models.TextField()),
                ("dosage", models.CharField(max_length=100)),
                ("precautions", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="recommended_supplements",
            field=models.ManyToManyField(blank=True, to="Mypage.supplement"),
        ),
        migrations.CreateModel(
            name="UserHealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health_score", models.IntegerField()),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Mypage.surveyresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
