# Generated by Django 5.2.1 on 2025-06-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0004_nutrient_nutrientanalysis_usernutrientintake"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutrientanalysis",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="nutrientanalysis",
            name="analysis_date",
        ),
        migrations.RemoveField(
            model_name="nutrientanalysis",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="current_supplements",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="drinking",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="exercise_frequency",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="fatigue",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="health_concerns",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="height",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="indoor_daytime",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="sitting_work",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="sleep_hours",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="sleep_well",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="smoking",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="still_tired",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="water_intake",
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="weight",
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="answers",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="result",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="nutrientanalysis",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="nutrientanalysis",
            name="overall_score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="surveyresult",
            name="health_status",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.RemoveField(
            model_name="surveyresult",
            name="recommended_supplements",
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="recommended_supplements",
            field=models.JSONField(default=list),
        ),
    ]
