# Generated by Django 5.2.1 on 2025-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0005_alter_nutrientanalysis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="sleep_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
