# Generated by Django 5.2.1 on 2025-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0006_surveyresponse_sleep_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="exercise_frequency",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
