# Generated by Django 5.2.1 on 2025-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0007_surveyresponse_exercise_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="water_intake",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
