# Generated by Django 5.2.1 on 2025-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mypage", "0008_surveyresponse_water_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="health_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
