# Generated by Django 5.2.1 on 2025-06-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=500)),
                ("url_images", models.TextField(blank=True)),
                ("safety_info", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("directions", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("flavor", models.CharField(blank=True, max_length=100)),
                ("supplement_type", models.CharField(blank=True, max_length=100)),
                ("quantity", models.CharField(blank=True, max_length=100)),
                ("product_form", models.CharField(blank=True, max_length=100)),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("total_reviews", models.IntegerField(blank=True, null=True)),
                ("rating_distribution", models.TextField(blank=True)),
                ("image_link", models.URLField(blank=True)),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("price_value", models.FloatField(blank=True, null=True)),
                ("diet_type", models.CharField(blank=True, max_length=100)),
                ("vegan", models.CharField(blank=True, max_length=30)),
                ("first_available_date", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                ("sales_ranks", models.TextField(blank=True)),
                ("popularity_score", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("stars", models.FloatField()),
                ("text", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Product.products",
                    ),
                ),
            ],
        ),
    ]
