version: "3"

services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "root1234"
      POSTGRES_DB: "topDB"
      POSTGRES_USER: "topAdmin"
    ports:
      - "5432:5432"

# docker-compose up -d
