# Generated by Django 5.2.1 on 2025-06-05 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=100)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ChatRooms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("health_conditions", models.TextField(blank=True)),
                ("used_products", models.TextField(blank=True)),
                (
                    "chat_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="Chatbot.chatrooms",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender_type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="Chatbot.chatrooms",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("input_prompt", models.TextField()),
                ("llm_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("model", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "recommended_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="Product.products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationStat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("liked_count", models.PositiveIntegerField(default=0)),
                ("recommended_count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_stat",
                        to="Product.products",
                    ),
                ),
            ],
        ),
    ]
